// This code conforms with the UFC specification version 2.0.5
// and was automatically generated by FFC version 1.0.0.
//
// This code was generated with the option '-l dolfin' and
// contains DOLFIN-specific wrappers that depend on DOLFIN.
// 
// This code was generated with the following parameters:
// 
//   cache_dir:                      ''
//   convert_exceptions_to_warnings: False
//   cpp_optimize:                   False
//   cpp_optimize_flags:             '-O2'
//   epsilon:                        1e-14
//   error_control:                  False
//   form_postfix:                   True
//   format:                         'dolfin'
//   log_level:                      20
//   log_prefix:                     ''
//   optimize:                       True
//   output_dir:                     '.'
//   precision:                      15
//   quadrature_degree:              'auto'
//   quadrature_rule:                'auto'
//   representation:                 'quadrature'
//   split:                          True
//   swig_binary:                    'swig'
//   swig_path:                      ''

#ifndef __BLOCH_TORREY_H
#define __BLOCH_TORREY_H

#include <cmath>
#include <stdexcept>
#include <fstream>
#include <ufc.h>

/// This class defines the interface for a finite element.

class bloch_torrey_finite_element_0: public ufc::finite_element
{
public:

  /// Constructor
  bloch_torrey_finite_element_0();

  /// Destructor
  virtual ~bloch_torrey_finite_element_0();

  /// Return a string identifying the finite element
  virtual const char* signature() const;

  /// Return the cell shape
  virtual ufc::shape cell_shape() const;

#ifndef UFC_BACKWARD_COMPATIBILITY
  /// Return the topological dimension of the cell shape
  virtual unsigned int topological_dimension() const;

  /// Return the geometric dimension of the cell shape
  virtual unsigned int geometric_dimension() const;
#endif
  /// Return the dimension of the finite element function space
  virtual unsigned int space_dimension() const;

  /// Return the rank of the value space
  virtual unsigned int value_rank() const;

  /// Return the dimension of the value space for axis i
  virtual unsigned int value_dimension(unsigned int i) const;

  /// Evaluate basis function i at given point in cell
  virtual void evaluate_basis(unsigned int i,
                              double* values,
                              const double* coordinates,
                              const ufc::cell& c) const;

  /// Evaluate all basis functions at given point in cell
  virtual void evaluate_basis_all(double* values,
                                  const double* coordinates,
                                  const ufc::cell& c) const;

  /// Evaluate order n derivatives of basis function i at given point in cell
  virtual void evaluate_basis_derivatives(unsigned int i,
                                          unsigned int n,
                                          double* values,
                                          const double* coordinates,
                                          const ufc::cell& c) const;

  /// Evaluate order n derivatives of all basis functions at given point in cell
  virtual void evaluate_basis_derivatives_all(unsigned int n,
                                              double* values,
                                              const double* coordinates,
                                              const ufc::cell& c) const;

  /// Evaluate linear functional for dof i on the function f
  virtual double evaluate_dof(unsigned int i,
                              const ufc::function& f,
                              const ufc::cell& c) const;

  /// Evaluate linear functionals for all dofs on the function f
  virtual void evaluate_dofs(double* values,
                             const ufc::function& f,
                             const ufc::cell& c) const;

  /// Interpolate vertex values from dof values
  virtual void interpolate_vertex_values(double* vertex_values,
                                         const double* dof_values,
                                         const ufc::cell& c) const;

#ifndef UFC_BACKWARD_COMPATIBILITY
  /// Map coordinate xhat from reference cell to coordinate x in cell
  virtual void map_from_reference_cell(double* x,
                                       const double* xhat,
                                       const ufc::cell& c) const;

  /// Map from coordinate x in cell to coordinate xhat in reference cell
  virtual void map_to_reference_cell(double* xhat,
                                     const double* x,
                                     const ufc::cell& c) const;
#endif

  /// Return the number of sub elements (for a mixed element)
  virtual unsigned int num_sub_elements() const;

  /// Create a new finite element for sub element i (for a mixed element)
  virtual ufc::finite_element* create_sub_element(unsigned int i) const;

#ifndef UFC_BACKWARD_COMPATIBILITY
  /// Create a new class instance
  virtual ufc::finite_element* create() const;

#endif
};

/// This class defines the interface for a finite element.

class bloch_torrey_finite_element_1: public ufc::finite_element
{
public:

  /// Constructor
  bloch_torrey_finite_element_1();

  /// Destructor
  virtual ~bloch_torrey_finite_element_1();

  /// Return a string identifying the finite element
  virtual const char* signature() const;

  /// Return the cell shape
  virtual ufc::shape cell_shape() const;

#ifndef UFC_BACKWARD_COMPATIBILITY
  /// Return the topological dimension of the cell shape
  virtual unsigned int topological_dimension() const;

  /// Return the geometric dimension of the cell shape
  virtual unsigned int geometric_dimension() const;
#endif
  /// Return the dimension of the finite element function space
  virtual unsigned int space_dimension() const;

  /// Return the rank of the value space
  virtual unsigned int value_rank() const;

  /// Return the dimension of the value space for axis i
  virtual unsigned int value_dimension(unsigned int i) const;

  /// Evaluate basis function i at given point in cell
  virtual void evaluate_basis(unsigned int i,
                              double* values,
                              const double* coordinates,
                              const ufc::cell& c) const;

  /// Evaluate all basis functions at given point in cell
  virtual void evaluate_basis_all(double* values,
                                  const double* coordinates,
                                  const ufc::cell& c) const;

  /// Evaluate order n derivatives of basis function i at given point in cell
  virtual void evaluate_basis_derivatives(unsigned int i,
                                          unsigned int n,
                                          double* values,
                                          const double* coordinates,
                                          const ufc::cell& c) const;

  /// Evaluate order n derivatives of all basis functions at given point in cell
  virtual void evaluate_basis_derivatives_all(unsigned int n,
                                              double* values,
                                              const double* coordinates,
                                              const ufc::cell& c) const;

  /// Evaluate linear functional for dof i on the function f
  virtual double evaluate_dof(unsigned int i,
                              const ufc::function& f,
                              const ufc::cell& c) const;

  /// Evaluate linear functionals for all dofs on the function f
  virtual void evaluate_dofs(double* values,
                             const ufc::function& f,
                             const ufc::cell& c) const;

  /// Interpolate vertex values from dof values
  virtual void interpolate_vertex_values(double* vertex_values,
                                         const double* dof_values,
                                         const ufc::cell& c) const;

#ifndef UFC_BACKWARD_COMPATIBILITY
  /// Map coordinate xhat from reference cell to coordinate x in cell
  virtual void map_from_reference_cell(double* x,
                                       const double* xhat,
                                       const ufc::cell& c) const;

  /// Map from coordinate x in cell to coordinate xhat in reference cell
  virtual void map_to_reference_cell(double* xhat,
                                     const double* x,
                                     const ufc::cell& c) const;
#endif

  /// Return the number of sub elements (for a mixed element)
  virtual unsigned int num_sub_elements() const;

  /// Create a new finite element for sub element i (for a mixed element)
  virtual ufc::finite_element* create_sub_element(unsigned int i) const;

#ifndef UFC_BACKWARD_COMPATIBILITY
  /// Create a new class instance
  virtual ufc::finite_element* create() const;

#endif
};

/// This class defines the interface for a finite element.

class bloch_torrey_finite_element_2: public ufc::finite_element
{
public:

  /// Constructor
  bloch_torrey_finite_element_2();

  /// Destructor
  virtual ~bloch_torrey_finite_element_2();

  /// Return a string identifying the finite element
  virtual const char* signature() const;

  /// Return the cell shape
  virtual ufc::shape cell_shape() const;

#ifndef UFC_BACKWARD_COMPATIBILITY
  /// Return the topological dimension of the cell shape
  virtual unsigned int topological_dimension() const;

  /// Return the geometric dimension of the cell shape
  virtual unsigned int geometric_dimension() const;
#endif
  /// Return the dimension of the finite element function space
  virtual unsigned int space_dimension() const;

  /// Return the rank of the value space
  virtual unsigned int value_rank() const;

  /// Return the dimension of the value space for axis i
  virtual unsigned int value_dimension(unsigned int i) const;

  /// Evaluate basis function i at given point in cell
  virtual void evaluate_basis(unsigned int i,
                              double* values,
                              const double* coordinates,
                              const ufc::cell& c) const;

  /// Evaluate all basis functions at given point in cell
  virtual void evaluate_basis_all(double* values,
                                  const double* coordinates,
                                  const ufc::cell& c) const;

  /// Evaluate order n derivatives of basis function i at given point in cell
  virtual void evaluate_basis_derivatives(unsigned int i,
                                          unsigned int n,
                                          double* values,
                                          const double* coordinates,
                                          const ufc::cell& c) const;

  /// Evaluate order n derivatives of all basis functions at given point in cell
  virtual void evaluate_basis_derivatives_all(unsigned int n,
                                              double* values,
                                              const double* coordinates,
                                              const ufc::cell& c) const;

  /// Evaluate linear functional for dof i on the function f
  virtual double evaluate_dof(unsigned int i,
                              const ufc::function& f,
                              const ufc::cell& c) const;

  /// Evaluate linear functionals for all dofs on the function f
  virtual void evaluate_dofs(double* values,
                             const ufc::function& f,
                             const ufc::cell& c) const;

  /// Interpolate vertex values from dof values
  virtual void interpolate_vertex_values(double* vertex_values,
                                         const double* dof_values,
                                         const ufc::cell& c) const;

#ifndef UFC_BACKWARD_COMPATIBILITY
  /// Map coordinate xhat from reference cell to coordinate x in cell
  virtual void map_from_reference_cell(double* x,
                                       const double* xhat,
                                       const ufc::cell& c) const;

  /// Map from coordinate x in cell to coordinate xhat in reference cell
  virtual void map_to_reference_cell(double* xhat,
                                     const double* x,
                                     const ufc::cell& c) const;
#endif

  /// Return the number of sub elements (for a mixed element)
  virtual unsigned int num_sub_elements() const;

  /// Create a new finite element for sub element i (for a mixed element)
  virtual ufc::finite_element* create_sub_element(unsigned int i) const;

#ifndef UFC_BACKWARD_COMPATIBILITY
  /// Create a new class instance
  virtual ufc::finite_element* create() const;

#endif
};

/// This class defines the interface for a local-to-global mapping of
/// degrees of freedom (dofs).

#ifndef UFC_BACKWARD_COMPATIBILITY
class bloch_torrey_dofmap_0: public ufc::dofmap
#else
class bloch_torrey_dofmap_0: public ufc::dof_map
#endif
{
private:

  unsigned int _global_dimension;
public:

  /// Constructor
  bloch_torrey_dofmap_0();

  /// Destructor
  virtual ~bloch_torrey_dofmap_0();

  /// Return a string identifying the dofmap
  virtual const char* signature() const;

  /// Return true iff mesh entities of topological dimension d are needed
  virtual bool needs_mesh_entities(unsigned int d) const;

  /// Initialize dofmap for mesh (return true iff init_cell() is needed)
  virtual bool init_mesh(const ufc::mesh& m);

  /// Initialize dofmap for given cell
  virtual void init_cell(const ufc::mesh& m,
                         const ufc::cell& c);

  /// Finish initialization of dofmap for cells
  virtual void init_cell_finalize();

#ifndef UFC_BACKWARD_COMPATIBILITY
  /// Return the topological dimension of the associated cell shape
  virtual unsigned int topological_dimension() const;

  /// Return the geometric dimension of the associated cell shape
  virtual unsigned int geometric_dimension() const;
#endif

  /// Return the dimension of the global finite element function space
  virtual unsigned int global_dimension() const;

#ifndef UFC_BACKWARD_COMPATIBILITY
  /// Return the dimension of the local finite element function space for a cell
  virtual unsigned int local_dimension(const ufc::cell& c) const;

  /// Return the maximum dimension of the local finite element function space
  virtual unsigned int max_local_dimension() const;
#else

  /// Return the dimension of the local finite element function space for a cell
  virtual unsigned int local_dimension() const;

  /// Return the maximum dimension of the local finite element function space
  virtual unsigned int geometric_dimension() const;
#endif
  /// Return the number of dofs on each cell facet
  virtual unsigned int num_facet_dofs() const;

  /// Return the number of dofs associated with each cell entity of dimension d
  virtual unsigned int num_entity_dofs(unsigned int d) const;

  /// Tabulate the local-to-global mapping of dofs on a cell
  virtual void tabulate_dofs(unsigned int* dofs,
                             const ufc::mesh& m,
                             const ufc::cell& c) const;

  /// Tabulate the local-to-local mapping from facet dofs to cell dofs
  virtual void tabulate_facet_dofs(unsigned int* dofs,
                                   unsigned int facet) const;

  /// Tabulate the local-to-local mapping of dofs on entity (d, i)
  virtual void tabulate_entity_dofs(unsigned int* dofs,
                                    unsigned int d, unsigned int i) const;

  /// Tabulate the coordinates of all dofs on a cell
  virtual void tabulate_coordinates(double** coordinates,
                                    const ufc::cell& c) const;

#ifndef UFC_BACKWARD_COMPATIBILITY
  /// Return the number of sub dofmaps (for a mixed element)
  virtual unsigned int num_sub_dofmaps() const;

  /// Create a new dofmap for sub dofmap i (for a mixed element)
  virtual ufc::dofmap* create_sub_dofmap(unsigned int i) const;

  /// Create a new class instance
  virtual ufc::dofmap* create() const;
#else
  /// Return the number of sub dofmaps (for a mixed element)
  virtual unsigned int num_sub_dof_maps() const;

  /// Create a new dofmap for sub dofmap i (for a mixed element)
  virtual ufc::dof_map* create_sub_dof_map(unsigned int i) const;
#endif
};

/// This class defines the interface for a local-to-global mapping of
/// degrees of freedom (dofs).

#ifndef UFC_BACKWARD_COMPATIBILITY
class bloch_torrey_dofmap_1: public ufc::dofmap
#else
class bloch_torrey_dofmap_1: public ufc::dof_map
#endif
{
private:

  unsigned int _global_dimension;
public:

  /// Constructor
  bloch_torrey_dofmap_1();

  /// Destructor
  virtual ~bloch_torrey_dofmap_1();

  /// Return a string identifying the dofmap
  virtual const char* signature() const;

  /// Return true iff mesh entities of topological dimension d are needed
  virtual bool needs_mesh_entities(unsigned int d) const;

  /// Initialize dofmap for mesh (return true iff init_cell() is needed)
  virtual bool init_mesh(const ufc::mesh& m);

  /// Initialize dofmap for given cell
  virtual void init_cell(const ufc::mesh& m,
                         const ufc::cell& c);

  /// Finish initialization of dofmap for cells
  virtual void init_cell_finalize();

#ifndef UFC_BACKWARD_COMPATIBILITY
  /// Return the topological dimension of the associated cell shape
  virtual unsigned int topological_dimension() const;

  /// Return the geometric dimension of the associated cell shape
  virtual unsigned int geometric_dimension() const;
#endif

  /// Return the dimension of the global finite element function space
  virtual unsigned int global_dimension() const;

#ifndef UFC_BACKWARD_COMPATIBILITY
  /// Return the dimension of the local finite element function space for a cell
  virtual unsigned int local_dimension(const ufc::cell& c) const;

  /// Return the maximum dimension of the local finite element function space
  virtual unsigned int max_local_dimension() const;
#else

  /// Return the dimension of the local finite element function space for a cell
  virtual unsigned int local_dimension() const;

  /// Return the maximum dimension of the local finite element function space
  virtual unsigned int geometric_dimension() const;
#endif
  /// Return the number of dofs on each cell facet
  virtual unsigned int num_facet_dofs() const;

  /// Return the number of dofs associated with each cell entity of dimension d
  virtual unsigned int num_entity_dofs(unsigned int d) const;

  /// Tabulate the local-to-global mapping of dofs on a cell
  virtual void tabulate_dofs(unsigned int* dofs,
                             const ufc::mesh& m,
                             const ufc::cell& c) const;

  /// Tabulate the local-to-local mapping from facet dofs to cell dofs
  virtual void tabulate_facet_dofs(unsigned int* dofs,
                                   unsigned int facet) const;

  /// Tabulate the local-to-local mapping of dofs on entity (d, i)
  virtual void tabulate_entity_dofs(unsigned int* dofs,
                                    unsigned int d, unsigned int i) const;

  /// Tabulate the coordinates of all dofs on a cell
  virtual void tabulate_coordinates(double** coordinates,
                                    const ufc::cell& c) const;

#ifndef UFC_BACKWARD_COMPATIBILITY
  /// Return the number of sub dofmaps (for a mixed element)
  virtual unsigned int num_sub_dofmaps() const;

  /// Create a new dofmap for sub dofmap i (for a mixed element)
  virtual ufc::dofmap* create_sub_dofmap(unsigned int i) const;

  /// Create a new class instance
  virtual ufc::dofmap* create() const;
#else
  /// Return the number of sub dofmaps (for a mixed element)
  virtual unsigned int num_sub_dof_maps() const;

  /// Create a new dofmap for sub dofmap i (for a mixed element)
  virtual ufc::dof_map* create_sub_dof_map(unsigned int i) const;
#endif
};

/// This class defines the interface for a local-to-global mapping of
/// degrees of freedom (dofs).

#ifndef UFC_BACKWARD_COMPATIBILITY
class bloch_torrey_dofmap_2: public ufc::dofmap
#else
class bloch_torrey_dofmap_2: public ufc::dof_map
#endif
{
private:

  unsigned int _global_dimension;
public:

  /// Constructor
  bloch_torrey_dofmap_2();

  /// Destructor
  virtual ~bloch_torrey_dofmap_2();

  /// Return a string identifying the dofmap
  virtual const char* signature() const;

  /// Return true iff mesh entities of topological dimension d are needed
  virtual bool needs_mesh_entities(unsigned int d) const;

  /// Initialize dofmap for mesh (return true iff init_cell() is needed)
  virtual bool init_mesh(const ufc::mesh& m);

  /// Initialize dofmap for given cell
  virtual void init_cell(const ufc::mesh& m,
                         const ufc::cell& c);

  /// Finish initialization of dofmap for cells
  virtual void init_cell_finalize();

#ifndef UFC_BACKWARD_COMPATIBILITY
  /// Return the topological dimension of the associated cell shape
  virtual unsigned int topological_dimension() const;

  /// Return the geometric dimension of the associated cell shape
  virtual unsigned int geometric_dimension() const;
#endif

  /// Return the dimension of the global finite element function space
  virtual unsigned int global_dimension() const;

#ifndef UFC_BACKWARD_COMPATIBILITY
  /// Return the dimension of the local finite element function space for a cell
  virtual unsigned int local_dimension(const ufc::cell& c) const;

  /// Return the maximum dimension of the local finite element function space
  virtual unsigned int max_local_dimension() const;
#else

  /// Return the dimension of the local finite element function space for a cell
  virtual unsigned int local_dimension() const;

  /// Return the maximum dimension of the local finite element function space
  virtual unsigned int geometric_dimension() const;
#endif
  /// Return the number of dofs on each cell facet
  virtual unsigned int num_facet_dofs() const;

  /// Return the number of dofs associated with each cell entity of dimension d
  virtual unsigned int num_entity_dofs(unsigned int d) const;

  /// Tabulate the local-to-global mapping of dofs on a cell
  virtual void tabulate_dofs(unsigned int* dofs,
                             const ufc::mesh& m,
                             const ufc::cell& c) const;

  /// Tabulate the local-to-local mapping from facet dofs to cell dofs
  virtual void tabulate_facet_dofs(unsigned int* dofs,
                                   unsigned int facet) const;

  /// Tabulate the local-to-local mapping of dofs on entity (d, i)
  virtual void tabulate_entity_dofs(unsigned int* dofs,
                                    unsigned int d, unsigned int i) const;

  /// Tabulate the coordinates of all dofs on a cell
  virtual void tabulate_coordinates(double** coordinates,
                                    const ufc::cell& c) const;

#ifndef UFC_BACKWARD_COMPATIBILITY
  /// Return the number of sub dofmaps (for a mixed element)
  virtual unsigned int num_sub_dofmaps() const;

  /// Create a new dofmap for sub dofmap i (for a mixed element)
  virtual ufc::dofmap* create_sub_dofmap(unsigned int i) const;

  /// Create a new class instance
  virtual ufc::dofmap* create() const;
#else
  /// Return the number of sub dofmaps (for a mixed element)
  virtual unsigned int num_sub_dof_maps() const;

  /// Create a new dofmap for sub dofmap i (for a mixed element)
  virtual ufc::dof_map* create_sub_dof_map(unsigned int i) const;
#endif
};

/// This class defines the interface for the tabulation of the cell
/// tensor corresponding to the local contribution to a form from
/// the integral over a cell.

class bloch_torrey_cell_integral_0_0: public ufc::cell_integral
{
public:

  /// Constructor
  bloch_torrey_cell_integral_0_0();

  /// Destructor
  virtual ~bloch_torrey_cell_integral_0_0();

  /// Tabulate the tensor for the contribution from a local cell
  virtual void tabulate_tensor(double* A,
                               const double * const * w,
                               const ufc::cell& c) const;

 #ifndef UFC_BACKWARD_COMPATIBILITY 
  /// Tabulate the tensor for the contribution from a local cell
  /// using the specified reference cell quadrature points/weights
  virtual void tabulate_tensor(double* A,
                               const double * const * w,
                               const ufc::cell& c,
                               unsigned int num_quadrature_points,
                               const double * const * quadrature_points,
                               const double* quadrature_weights) const;
#endif
};

/// This class defines the interface for the tabulation of the
/// interior facet tensor corresponding to the local contribution to
/// a form from the integral over an interior facet.

class bloch_torrey_interior_facet_integral_0_0: public ufc::interior_facet_integral
{
public:

  /// Constructor
  bloch_torrey_interior_facet_integral_0_0();

  /// Destructor
  virtual ~bloch_torrey_interior_facet_integral_0_0();

  /// Tabulate the tensor for the contribution from a local interior facet
  virtual void tabulate_tensor(double* A,
                               const double * const * w,
                               const ufc::cell& c0,
                               const ufc::cell& c1,
                               unsigned int facet0,
                               unsigned int facet1) const;

 #ifndef UFC_BACKWARD_COMPATIBILITY 
  /// Tabulate the tensor for the contribution from a local interior facet
  /// using the specified reference cell quadrature points/weights
  virtual void tabulate_tensor(double* A,
                               const double * const * w,
                               const ufc::cell& c,
                               unsigned int num_quadrature_points,
                               const double * const * quadrature_points,
                               const double* quadrature_weights) const;
#endif
};

/// This class defines the interface for the tabulation of the cell
/// tensor corresponding to the local contribution to a form from
/// the integral over a cell.

class bloch_torrey_cell_integral_1_0: public ufc::cell_integral
{
public:

  /// Constructor
  bloch_torrey_cell_integral_1_0();

  /// Destructor
  virtual ~bloch_torrey_cell_integral_1_0();

  /// Tabulate the tensor for the contribution from a local cell
  virtual void tabulate_tensor(double* A,
                               const double * const * w,
                               const ufc::cell& c) const;

 #ifndef UFC_BACKWARD_COMPATIBILITY 
  /// Tabulate the tensor for the contribution from a local cell
  /// using the specified reference cell quadrature points/weights
  virtual void tabulate_tensor(double* A,
                               const double * const * w,
                               const ufc::cell& c,
                               unsigned int num_quadrature_points,
                               const double * const * quadrature_points,
                               const double* quadrature_weights) const;
#endif
};

/// This class defines the interface for the tabulation of the
/// interior facet tensor corresponding to the local contribution to
/// a form from the integral over an interior facet.

class bloch_torrey_interior_facet_integral_1_0: public ufc::interior_facet_integral
{
public:

  /// Constructor
  bloch_torrey_interior_facet_integral_1_0();

  /// Destructor
  virtual ~bloch_torrey_interior_facet_integral_1_0();

  /// Tabulate the tensor for the contribution from a local interior facet
  virtual void tabulate_tensor(double* A,
                               const double * const * w,
                               const ufc::cell& c0,
                               const ufc::cell& c1,
                               unsigned int facet0,
                               unsigned int facet1) const;

 #ifndef UFC_BACKWARD_COMPATIBILITY 
  /// Tabulate the tensor for the contribution from a local interior facet
  /// using the specified reference cell quadrature points/weights
  virtual void tabulate_tensor(double* A,
                               const double * const * w,
                               const ufc::cell& c,
                               unsigned int num_quadrature_points,
                               const double * const * quadrature_points,
                               const double* quadrature_weights) const;
#endif
};

/// This class defines the interface for the assembly of the global
/// tensor corresponding to a form with r + n arguments, that is, a
/// mapping
///
///     a : V1 x V2 x ... Vr x W1 x W2 x ... x Wn -> R
///
/// with arguments v1, v2, ..., vr, w1, w2, ..., wn. The rank r
/// global tensor A is defined by
///
///     A = a(V1, V2, ..., Vr, w1, w2, ..., wn),
///
/// where each argument Vj represents the application to the
/// sequence of basis functions of Vj and w1, w2, ..., wn are given
/// fixed functions (coefficients).

class bloch_torrey_form_0: public ufc::form
{
public:

  /// Constructor
  bloch_torrey_form_0();

  /// Destructor
  virtual ~bloch_torrey_form_0();

  /// Return a string identifying the form
  virtual const char* signature() const;

  /// Return the rank of the global tensor (r)
  virtual unsigned int rank() const;

  /// Return the number of coefficients (n)
  virtual unsigned int num_coefficients() const;

 #ifndef UFC_BACKWARD_COMPATIBILITY 
  /// Return the number of cell domains
  virtual unsigned int num_cell_domains() const;

  /// Return the number of exterior facet domains
  virtual unsigned int num_exterior_facet_domains() const;

  /// Return the number of interior facet domains
  virtual unsigned int num_interior_facet_domains() const;
#else
  /// Return the number of cell domains
  virtual unsigned int num_cell_integrals() const;

  /// Return the number of exterior facet domains
  virtual unsigned int num_exterior_facet_integrals() const;

  /// Return the number of interior facet domains
  virtual unsigned int num_interior_facet_integrals() const;

#endif
  /// Create a new finite element for argument function i
  virtual ufc::finite_element* create_finite_element(unsigned int i) const;

 #ifndef UFC_BACKWARD_COMPATIBILITY 
  /// Create a new dofmap for argument function i
  virtual ufc::dofmap* create_dofmap(unsigned int i) const;
#else
  /// Create a new dofmap for argument function i
  virtual ufc::dof_map* create_dof_map(unsigned int i) const;

#endif
  /// Create a new cell integral on sub domain i
  virtual ufc::cell_integral* create_cell_integral(unsigned int i) const;

  /// Create a new exterior facet integral on sub domain i
  virtual ufc::exterior_facet_integral* create_exterior_facet_integral(unsigned int i) const;

  /// Create a new interior facet integral on sub domain i
  virtual ufc::interior_facet_integral* create_interior_facet_integral(unsigned int i) const;

};

/// This class defines the interface for the assembly of the global
/// tensor corresponding to a form with r + n arguments, that is, a
/// mapping
///
///     a : V1 x V2 x ... Vr x W1 x W2 x ... x Wn -> R
///
/// with arguments v1, v2, ..., vr, w1, w2, ..., wn. The rank r
/// global tensor A is defined by
///
///     A = a(V1, V2, ..., Vr, w1, w2, ..., wn),
///
/// where each argument Vj represents the application to the
/// sequence of basis functions of Vj and w1, w2, ..., wn are given
/// fixed functions (coefficients).

class bloch_torrey_form_1: public ufc::form
{
public:

  /// Constructor
  bloch_torrey_form_1();

  /// Destructor
  virtual ~bloch_torrey_form_1();

  /// Return a string identifying the form
  virtual const char* signature() const;

  /// Return the rank of the global tensor (r)
  virtual unsigned int rank() const;

  /// Return the number of coefficients (n)
  virtual unsigned int num_coefficients() const;

 #ifndef UFC_BACKWARD_COMPATIBILITY 
  /// Return the number of cell domains
  virtual unsigned int num_cell_domains() const;

  /// Return the number of exterior facet domains
  virtual unsigned int num_exterior_facet_domains() const;

  /// Return the number of interior facet domains
  virtual unsigned int num_interior_facet_domains() const;
#else
  /// Return the number of cell domains
  virtual unsigned int num_cell_integrals() const;

  /// Return the number of exterior facet domains
  virtual unsigned int num_exterior_facet_integrals() const;

  /// Return the number of interior facet domains
  virtual unsigned int num_interior_facet_integrals() const;

#endif
  /// Create a new finite element for argument function i
  virtual ufc::finite_element* create_finite_element(unsigned int i) const;

 #ifndef UFC_BACKWARD_COMPATIBILITY 
  /// Create a new dofmap for argument function i
  virtual ufc::dofmap* create_dofmap(unsigned int i) const;
#else
  /// Create a new dofmap for argument function i
  virtual ufc::dof_map* create_dof_map(unsigned int i) const;

#endif
  /// Create a new cell integral on sub domain i
  virtual ufc::cell_integral* create_cell_integral(unsigned int i) const;

  /// Create a new exterior facet integral on sub domain i
  virtual ufc::exterior_facet_integral* create_exterior_facet_integral(unsigned int i) const;

  /// Create a new interior facet integral on sub domain i
  virtual ufc::interior_facet_integral* create_interior_facet_integral(unsigned int i) const;

};

#ifndef UFC_BACKWARD_COMPATIBILITY 

// DOLFIN wrappers

// Standard library includes
#include <string>

// DOLFIN includes
#include <dolfin/common/NoDeleter.h>
#include <dolfin/fem/FiniteElement.h>
#include <dolfin/fem/DofMap.h>
#include <dolfin/fem/Form.h>
#include <dolfin/function/FunctionSpace.h>
#include <dolfin/function/GenericFunction.h>
#include <dolfin/function/CoefficientAssigner.h>
#include <dolfin/adaptivity/ErrorControl.h>
#include <dolfin/adaptivity/GoalFunctional.h>

namespace Bloch_Torrey
{

class CoefficientSpace_GX: public dolfin::FunctionSpace
{
public:

  CoefficientSpace_GX(const dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap *(new dolfin::DofMap(ufc::dofmap* (new bloch_torrey_dofmap_1()), mesh)))
  {
    // Do nothing
  }

  CoefficientSpace_GX(dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap *(new bloch_torrey_dofmap_1()), mesh)))
  {
    // Do nothing
  }

  CoefficientSpace_GX(dolfin::Mesh*  mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_1()), *mesh)))
  {
      // Do nothing
  }

  CoefficientSpace_GX(const dolfin::Mesh* mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element*(new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap*(new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_1()), *mesh)))
  {
      // Do nothing
  }

  ~CoefficientSpace_GX()
  {
  }

};

class CoefficientSpace_K: public dolfin::FunctionSpace
{
public:

  CoefficientSpace_K(const dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap *(new dolfin::DofMap(ufc::dofmap* (new bloch_torrey_dofmap_1()), mesh)))
  {
    // Do nothing
  }

  CoefficientSpace_K(dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap *(new bloch_torrey_dofmap_1()), mesh)))
  {
    // Do nothing
  }

  CoefficientSpace_K(dolfin::Mesh*  mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_1()), *mesh)))
  {
      // Do nothing
  }

  CoefficientSpace_K(const dolfin::Mesh* mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element*(new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap*(new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_1()), *mesh)))
  {
      // Do nothing
  }

  ~CoefficientSpace_K()
  {
  }

};

class CoefficientSpace_dt: public dolfin::FunctionSpace
{
public:

  CoefficientSpace_dt(const dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap *(new dolfin::DofMap(ufc::dofmap* (new bloch_torrey_dofmap_1()), mesh)))
  {
    // Do nothing
  }

  CoefficientSpace_dt(dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap *(new bloch_torrey_dofmap_1()), mesh)))
  {
    // Do nothing
  }

  CoefficientSpace_dt(dolfin::Mesh*  mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_1()), *mesh)))
  {
      // Do nothing
  }

  CoefficientSpace_dt(const dolfin::Mesh* mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element*(new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap*(new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_1()), *mesh)))
  {
      // Do nothing
  }

  ~CoefficientSpace_dt()
  {
  }

};

class CoefficientSpace_ft: public dolfin::FunctionSpace
{
public:

  CoefficientSpace_ft(const dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap *(new dolfin::DofMap(ufc::dofmap* (new bloch_torrey_dofmap_1()), mesh)))
  {
    // Do nothing
  }

  CoefficientSpace_ft(dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap *(new bloch_torrey_dofmap_1()), mesh)))
  {
    // Do nothing
  }

  CoefficientSpace_ft(dolfin::Mesh*  mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_1()), *mesh)))
  {
      // Do nothing
  }

  CoefficientSpace_ft(const dolfin::Mesh* mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element*(new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap*(new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_1()), *mesh)))
  {
      // Do nothing
  }

  ~CoefficientSpace_ft()
  {
  }

};

class CoefficientSpace_gnorm: public dolfin::FunctionSpace
{
public:

  CoefficientSpace_gnorm(const dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap *(new dolfin::DofMap(ufc::dofmap* (new bloch_torrey_dofmap_1()), mesh)))
  {
    // Do nothing
  }

  CoefficientSpace_gnorm(dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap *(new bloch_torrey_dofmap_1()), mesh)))
  {
    // Do nothing
  }

  CoefficientSpace_gnorm(dolfin::Mesh*  mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_1()), *mesh)))
  {
      // Do nothing
  }

  CoefficientSpace_gnorm(const dolfin::Mesh* mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element*(new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap*(new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_1()), *mesh)))
  {
      // Do nothing
  }

  ~CoefficientSpace_gnorm()
  {
  }

};

class CoefficientSpace_kappa: public dolfin::FunctionSpace
{
public:

  CoefficientSpace_kappa(const dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap *(new dolfin::DofMap(ufc::dofmap* (new bloch_torrey_dofmap_1()), mesh)))
  {
    // Do nothing
  }

  CoefficientSpace_kappa(dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap *(new bloch_torrey_dofmap_1()), mesh)))
  {
    // Do nothing
  }

  CoefficientSpace_kappa(dolfin::Mesh*  mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_1()), *mesh)))
  {
      // Do nothing
  }

  CoefficientSpace_kappa(const dolfin::Mesh* mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element*(new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap*(new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_1()), *mesh)))
  {
      // Do nothing
  }

  ~CoefficientSpace_kappa()
  {
  }

};

class CoefficientSpace_phase: public dolfin::FunctionSpace
{
public:

  CoefficientSpace_phase(const dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_0()))),
                          const dolfin::DofMap *(new dolfin::DofMap(ufc::dofmap* (new bloch_torrey_dofmap_0()), mesh)))
  {
    // Do nothing
  }

  CoefficientSpace_phase(dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_0()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap *(new bloch_torrey_dofmap_0()), mesh)))
  {
    // Do nothing
  }

  CoefficientSpace_phase(dolfin::Mesh*  mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_0()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_0()), *mesh)))
  {
      // Do nothing
  }

  CoefficientSpace_phase(const dolfin::Mesh* mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element*(new bloch_torrey_finite_element_0()))),
                          const dolfin::DofMap*(new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_0()), *mesh)))
  {
      // Do nothing
  }

  ~CoefficientSpace_phase()
  {
  }

};

class CoefficientSpace_theta: public dolfin::FunctionSpace
{
public:

  CoefficientSpace_theta(const dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap *(new dolfin::DofMap(ufc::dofmap* (new bloch_torrey_dofmap_1()), mesh)))
  {
    // Do nothing
  }

  CoefficientSpace_theta(dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap *(new bloch_torrey_dofmap_1()), mesh)))
  {
    // Do nothing
  }

  CoefficientSpace_theta(dolfin::Mesh*  mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_1()), *mesh)))
  {
      // Do nothing
  }

  CoefficientSpace_theta(const dolfin::Mesh* mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element*(new bloch_torrey_finite_element_1()))),
                          const dolfin::DofMap*(new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_1()), *mesh)))
  {
      // Do nothing
  }

  ~CoefficientSpace_theta()
  {
  }

};

class CoefficientSpace_u_0: public dolfin::FunctionSpace
{
public:

  CoefficientSpace_u_0(const dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_2()))),
                          const dolfin::DofMap *(new dolfin::DofMap(ufc::dofmap* (new bloch_torrey_dofmap_2()), mesh)))
  {
    // Do nothing
  }

  CoefficientSpace_u_0(dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_2()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap *(new bloch_torrey_dofmap_2()), mesh)))
  {
    // Do nothing
  }

  CoefficientSpace_u_0(dolfin::Mesh*  mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_2()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_2()), *mesh)))
  {
      // Do nothing
  }

  CoefficientSpace_u_0(const dolfin::Mesh* mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element*(new bloch_torrey_finite_element_2()))),
                          const dolfin::DofMap*(new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_2()), *mesh)))
  {
      // Do nothing
  }

  ~CoefficientSpace_u_0()
  {
  }

};

class Form_0_FunctionSpace_0: public dolfin::FunctionSpace
{
public:

  Form_0_FunctionSpace_0(const dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_2()))),
                          const dolfin::DofMap *(new dolfin::DofMap(ufc::dofmap* (new bloch_torrey_dofmap_2()), mesh)))
  {
    // Do nothing
  }

  Form_0_FunctionSpace_0(dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_2()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap *(new bloch_torrey_dofmap_2()), mesh)))
  {
    // Do nothing
  }

  Form_0_FunctionSpace_0(dolfin::Mesh*  mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_2()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_2()), *mesh)))
  {
      // Do nothing
  }

  Form_0_FunctionSpace_0(const dolfin::Mesh* mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element*(new bloch_torrey_finite_element_2()))),
                          const dolfin::DofMap*(new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_2()), *mesh)))
  {
      // Do nothing
  }

  ~Form_0_FunctionSpace_0()
  {
  }

};

class Form_0_FunctionSpace_1: public dolfin::FunctionSpace
{
public:

  Form_0_FunctionSpace_1(const dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_2()))),
                          const dolfin::DofMap *(new dolfin::DofMap(ufc::dofmap* (new bloch_torrey_dofmap_2()), mesh)))
  {
    // Do nothing
  }

  Form_0_FunctionSpace_1(dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_2()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap *(new bloch_torrey_dofmap_2()), mesh)))
  {
    // Do nothing
  }

  Form_0_FunctionSpace_1(dolfin::Mesh*  mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_2()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_2()), *mesh)))
  {
      // Do nothing
  }

  Form_0_FunctionSpace_1(const dolfin::Mesh* mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element*(new bloch_torrey_finite_element_2()))),
                          const dolfin::DofMap*(new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_2()), *mesh)))
  {
      // Do nothing
  }

  ~Form_0_FunctionSpace_1()
  {
  }

};

typedef CoefficientSpace_phase Form_0_FunctionSpace_2;

typedef CoefficientSpace_GX Form_0_FunctionSpace_3;

typedef CoefficientSpace_ft Form_0_FunctionSpace_4;

typedef CoefficientSpace_gnorm Form_0_FunctionSpace_5;

typedef CoefficientSpace_K Form_0_FunctionSpace_6;

typedef CoefficientSpace_kappa Form_0_FunctionSpace_7;

typedef CoefficientSpace_theta Form_0_FunctionSpace_8;

typedef CoefficientSpace_dt Form_0_FunctionSpace_9;

class Form_0: public dolfin::Form
{
public:

  // Constructor
  Form_0(const dolfin::FunctionSpace& V1, const dolfin::FunctionSpace& V0):
    dolfin::Form(2, 8), phase(*this, 0), GX(*this, 1), ft(*this, 2), gnorm(*this, 3), K(*this, 4), kappa(*this, 5), theta(*this, 6), dt(*this, 7)
  {
    _function_spaces[0] = reference_to_no_delete_pointer(V0);
    _function_spaces[1] = reference_to_no_delete_pointer(V1);

    _ufc_form = const ufc::form* (new bloch_torrey_form_0());
  }

  // Constructor
  Form_0(const dolfin::FunctionSpace& V1, const dolfin::FunctionSpace& V0, const dolfin::GenericFunction& phase, const dolfin::GenericFunction& GX, const dolfin::GenericFunction& ft, const dolfin::GenericFunction& gnorm, const dolfin::GenericFunction& K, const dolfin::GenericFunction& kappa, const dolfin::GenericFunction& theta, const dolfin::GenericFunction& dt):
    dolfin::Form(2, 8), phase(*this, 0), GX(*this, 1), ft(*this, 2), gnorm(*this, 3), K(*this, 4), kappa(*this, 5), theta(*this, 6), dt(*this, 7)
  {
    _function_spaces[0] = reference_to_no_delete_pointer(V0);
    _function_spaces[1] = reference_to_no_delete_pointer(V1);

    this->phase = phase;
    this->GX = GX;
    this->ft = ft;
    this->gnorm = gnorm;
    this->K = K;
    this->kappa = kappa;
    this->theta = theta;
    this->dt = dt;

    _ufc_form = const ufc::form* (new bloch_torrey_form_0());
  }

  // Constructor
  Form_0(const dolfin::FunctionSpace& V1, const dolfin::FunctionSpace& V0, boost::shared_ptr<const dolfin::GenericFunction> phase, boost::shared_ptr<const dolfin::GenericFunction> GX, boost::shared_ptr<const dolfin::GenericFunction> ft, boost::shared_ptr<const dolfin::GenericFunction> gnorm, boost::shared_ptr<const dolfin::GenericFunction> K, boost::shared_ptr<const dolfin::GenericFunction> kappa, boost::shared_ptr<const dolfin::GenericFunction> theta, boost::shared_ptr<const dolfin::GenericFunction> dt):
    dolfin::Form(2, 8), phase(*this, 0), GX(*this, 1), ft(*this, 2), gnorm(*this, 3), K(*this, 4), kappa(*this, 5), theta(*this, 6), dt(*this, 7)
  {
    _function_spaces[0] = reference_to_no_delete_pointer(V0);
    _function_spaces[1] = reference_to_no_delete_pointer(V1);

    this->phase = *phase;
    this->GX = *GX;
    this->ft = *ft;
    this->gnorm = *gnorm;
    this->K = *K;
    this->kappa = *kappa;
    this->theta = *theta;
    this->dt = *dt;

    _ufc_form = const ufc::form* (new bloch_torrey_form_0());
  }

  // Constructor
  Form_0(boost::shared_ptr<const dolfin::FunctionSpace> V1, boost::shared_ptr<const dolfin::FunctionSpace> V0):
    dolfin::Form(2, 8), phase(*this, 0), GX(*this, 1), ft(*this, 2), gnorm(*this, 3), K(*this, 4), kappa(*this, 5), theta(*this, 6), dt(*this, 7)
  {
    _function_spaces[0] = V0;
    _function_spaces[1] = V1;

    _ufc_form = const ufc::form* (new bloch_torrey_form_0());
  }

  // Constructor
  Form_0(boost::shared_ptr<const dolfin::FunctionSpace> V1, boost::shared_ptr<const dolfin::FunctionSpace> V0, const dolfin::GenericFunction& phase, const dolfin::GenericFunction& GX, const dolfin::GenericFunction& ft, const dolfin::GenericFunction& gnorm, const dolfin::GenericFunction& K, const dolfin::GenericFunction& kappa, const dolfin::GenericFunction& theta, const dolfin::GenericFunction& dt):
    dolfin::Form(2, 8), phase(*this, 0), GX(*this, 1), ft(*this, 2), gnorm(*this, 3), K(*this, 4), kappa(*this, 5), theta(*this, 6), dt(*this, 7)
  {
    _function_spaces[0] = V0;
    _function_spaces[1] = V1;

    this->phase = phase;
    this->GX = GX;
    this->ft = ft;
    this->gnorm = gnorm;
    this->K = K;
    this->kappa = kappa;
    this->theta = theta;
    this->dt = dt;

    _ufc_form = const ufc::form* (new bloch_torrey_form_0());
  }

  // Constructor
  Form_0(boost::shared_ptr<const dolfin::FunctionSpace> V1, boost::shared_ptr<const dolfin::FunctionSpace> V0, boost::shared_ptr<const dolfin::GenericFunction> phase, boost::shared_ptr<const dolfin::GenericFunction> GX, boost::shared_ptr<const dolfin::GenericFunction> ft, boost::shared_ptr<const dolfin::GenericFunction> gnorm, boost::shared_ptr<const dolfin::GenericFunction> K, boost::shared_ptr<const dolfin::GenericFunction> kappa, boost::shared_ptr<const dolfin::GenericFunction> theta, boost::shared_ptr<const dolfin::GenericFunction> dt):
    dolfin::Form(2, 8), phase(*this, 0), GX(*this, 1), ft(*this, 2), gnorm(*this, 3), K(*this, 4), kappa(*this, 5), theta(*this, 6), dt(*this, 7)
  {
    _function_spaces[0] = V0;
    _function_spaces[1] = V1;

    this->phase = *phase;
    this->GX = *GX;
    this->ft = *ft;
    this->gnorm = *gnorm;
    this->K = *K;
    this->kappa = *kappa;
    this->theta = *theta;
    this->dt = *dt;

    _ufc_form = const ufc::form* (new bloch_torrey_form_0());
  }

  // Destructor
  ~Form_0()
  {}

  /// Return the number of the coefficient with this name
  virtual dolfin::uint coefficient_number(const std::string& name) const
  {
    if (name == "phase")
      return 0;
    else if (name == "GX")
      return 1;
    else if (name == "ft")
      return 2;
    else if (name == "gnorm")
      return 3;
    else if (name == "K")
      return 4;
    else if (name == "kappa")
      return 5;
    else if (name == "theta")
      return 6;
    else if (name == "dt")
      return 7;

    dolfin::dolfin_error("generated code for class Form",
                         "access coeficient data",
                         "Invalid coeficient");
    return 0;
  }

  /// Return the name of the coefficient with this number
  virtual std::string coefficient_name(dolfin::uint i) const
  {
    switch (i)
    {
    case 0:
      return "phase";
    case 1:
      return "GX";
    case 2:
      return "ft";
    case 3:
      return "gnorm";
    case 4:
      return "K";
    case 5:
      return "kappa";
    case 6:
      return "theta";
    case 7:
      return "dt";
    }

    dolfin::dolfin_error("generated code for class Form",
                         "access coeficient data",
                         "Invalid coeficient");
    return "unnamed";
  }

  // Typedefs
  typedef Form_0_FunctionSpace_0 TestSpace;
  typedef Form_0_FunctionSpace_1 TrialSpace;
  typedef Form_0_FunctionSpace_2 CoefficientSpace_phase;
  typedef Form_0_FunctionSpace_3 CoefficientSpace_GX;
  typedef Form_0_FunctionSpace_4 CoefficientSpace_ft;
  typedef Form_0_FunctionSpace_5 CoefficientSpace_gnorm;
  typedef Form_0_FunctionSpace_6 CoefficientSpace_K;
  typedef Form_0_FunctionSpace_7 CoefficientSpace_kappa;
  typedef Form_0_FunctionSpace_8 CoefficientSpace_theta;
  typedef Form_0_FunctionSpace_9 CoefficientSpace_dt;

  // Coefficients
  dolfin::CoefficientAssigner phase;
  dolfin::CoefficientAssigner GX;
  dolfin::CoefficientAssigner ft;
  dolfin::CoefficientAssigner gnorm;
  dolfin::CoefficientAssigner K;
  dolfin::CoefficientAssigner kappa;
  dolfin::CoefficientAssigner theta;
  dolfin::CoefficientAssigner dt;
};

class Form_1_FunctionSpace_0: public dolfin::FunctionSpace
{
public:

  Form_1_FunctionSpace_0(const dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_2()))),
                          const dolfin::DofMap *(new dolfin::DofMap(ufc::dofmap* (new bloch_torrey_dofmap_2()), mesh)))
  {
    // Do nothing
  }

  Form_1_FunctionSpace_0(dolfin::Mesh& mesh):
    dolfin::FunctionSpace(dolfin::reference_to_no_delete_pointer(mesh),
                          const dolfin::FiniteElement* (new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_2()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap *(new bloch_torrey_dofmap_2()), mesh)))
  {
    // Do nothing
  }

  Form_1_FunctionSpace_0(dolfin::Mesh*  mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element* (new bloch_torrey_finite_element_2()))),
                          const dolfin::DofMap* (new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_2()), *mesh)))
  {
      // Do nothing
  }

  Form_1_FunctionSpace_0(const dolfin::Mesh* mesh):
    dolfin::FunctionSpace(mesh,
                          const dolfin::FiniteElement *(new dolfin::FiniteElement(ufc::finite_element*(new bloch_torrey_finite_element_2()))),
                          const dolfin::DofMap*(new dolfin::DofMap(ufc::dofmap*(new bloch_torrey_dofmap_2()), *mesh)))
  {
      // Do nothing
  }

  ~Form_1_FunctionSpace_0()
  {
  }

};

typedef CoefficientSpace_phase Form_1_FunctionSpace_1;

typedef CoefficientSpace_u_0 Form_1_FunctionSpace_2;

typedef CoefficientSpace_GX Form_1_FunctionSpace_3;

typedef CoefficientSpace_ft Form_1_FunctionSpace_4;

typedef CoefficientSpace_gnorm Form_1_FunctionSpace_5;

typedef CoefficientSpace_K Form_1_FunctionSpace_6;

typedef CoefficientSpace_kappa Form_1_FunctionSpace_7;

typedef CoefficientSpace_theta Form_1_FunctionSpace_8;

typedef CoefficientSpace_dt Form_1_FunctionSpace_9;

class Form_1: public dolfin::Form
{
public:

  // Constructor
  Form_1(const dolfin::FunctionSpace& V0):
    dolfin::Form(1, 9), phase(*this, 0), u_0(*this, 1), GX(*this, 2), ft(*this, 3), gnorm(*this, 4), K(*this, 5), kappa(*this, 6), theta(*this, 7), dt(*this, 8)
  {
    _function_spaces[0] = reference_to_no_delete_pointer(V0);

    _ufc_form = const ufc::form* (new bloch_torrey_form_1());
  }

  // Constructor
  Form_1(const dolfin::FunctionSpace& V0, const dolfin::GenericFunction& phase, const dolfin::GenericFunction& u_0, const dolfin::GenericFunction& GX, const dolfin::GenericFunction& ft, const dolfin::GenericFunction& gnorm, const dolfin::GenericFunction& K, const dolfin::GenericFunction& kappa, const dolfin::GenericFunction& theta, const dolfin::GenericFunction& dt):
    dolfin::Form(1, 9), phase(*this, 0), u_0(*this, 1), GX(*this, 2), ft(*this, 3), gnorm(*this, 4), K(*this, 5), kappa(*this, 6), theta(*this, 7), dt(*this, 8)
  {
    _function_spaces[0] = reference_to_no_delete_pointer(V0);

    this->phase = phase;
    this->u_0 = u_0;
    this->GX = GX;
    this->ft = ft;
    this->gnorm = gnorm;
    this->K = K;
    this->kappa = kappa;
    this->theta = theta;
    this->dt = dt;

    _ufc_form = const ufc::form* (new bloch_torrey_form_1());
  }

  // Constructor
  Form_1(const dolfin::FunctionSpace& V0, boost::shared_ptr<const dolfin::GenericFunction> phase, boost::shared_ptr<const dolfin::GenericFunction> u_0, boost::shared_ptr<const dolfin::GenericFunction> GX, boost::shared_ptr<const dolfin::GenericFunction> ft, boost::shared_ptr<const dolfin::GenericFunction> gnorm, boost::shared_ptr<const dolfin::GenericFunction> K, boost::shared_ptr<const dolfin::GenericFunction> kappa, boost::shared_ptr<const dolfin::GenericFunction> theta, boost::shared_ptr<const dolfin::GenericFunction> dt):
    dolfin::Form(1, 9), phase(*this, 0), u_0(*this, 1), GX(*this, 2), ft(*this, 3), gnorm(*this, 4), K(*this, 5), kappa(*this, 6), theta(*this, 7), dt(*this, 8)
  {
    _function_spaces[0] = reference_to_no_delete_pointer(V0);

    this->phase = *phase;
    this->u_0 = *u_0;
    this->GX = *GX;
    this->ft = *ft;
    this->gnorm = *gnorm;
    this->K = *K;
    this->kappa = *kappa;
    this->theta = *theta;
    this->dt = *dt;

    _ufc_form = const ufc::form* (new bloch_torrey_form_1());
  }

  // Constructor
  Form_1(boost::shared_ptr<const dolfin::FunctionSpace> V0):
    dolfin::Form(1, 9), phase(*this, 0), u_0(*this, 1), GX(*this, 2), ft(*this, 3), gnorm(*this, 4), K(*this, 5), kappa(*this, 6), theta(*this, 7), dt(*this, 8)
  {
    _function_spaces[0] = V0;

    _ufc_form = const ufc::form* (new bloch_torrey_form_1());
  }

  // Constructor
  Form_1(boost::shared_ptr<const dolfin::FunctionSpace> V0, const dolfin::GenericFunction& phase, const dolfin::GenericFunction& u_0, const dolfin::GenericFunction& GX, const dolfin::GenericFunction& ft, const dolfin::GenericFunction& gnorm, const dolfin::GenericFunction& K, const dolfin::GenericFunction& kappa, const dolfin::GenericFunction& theta, const dolfin::GenericFunction& dt):
    dolfin::Form(1, 9), phase(*this, 0), u_0(*this, 1), GX(*this, 2), ft(*this, 3), gnorm(*this, 4), K(*this, 5), kappa(*this, 6), theta(*this, 7), dt(*this, 8)
  {
    _function_spaces[0] = V0;

    this->phase = phase;
    this->u_0 = u_0;
    this->GX = GX;
    this->ft = ft;
    this->gnorm = gnorm;
    this->K = K;
    this->kappa = kappa;
    this->theta = theta;
    this->dt = dt;

    _ufc_form = const ufc::form* (new bloch_torrey_form_1());
  }

  // Constructor
  Form_1(boost::shared_ptr<const dolfin::FunctionSpace> V0, boost::shared_ptr<const dolfin::GenericFunction> phase, boost::shared_ptr<const dolfin::GenericFunction> u_0, boost::shared_ptr<const dolfin::GenericFunction> GX, boost::shared_ptr<const dolfin::GenericFunction> ft, boost::shared_ptr<const dolfin::GenericFunction> gnorm, boost::shared_ptr<const dolfin::GenericFunction> K, boost::shared_ptr<const dolfin::GenericFunction> kappa, boost::shared_ptr<const dolfin::GenericFunction> theta, boost::shared_ptr<const dolfin::GenericFunction> dt):
    dolfin::Form(1, 9), phase(*this, 0), u_0(*this, 1), GX(*this, 2), ft(*this, 3), gnorm(*this, 4), K(*this, 5), kappa(*this, 6), theta(*this, 7), dt(*this, 8)
  {
    _function_spaces[0] = V0;

    this->phase = *phase;
    this->u_0 = *u_0;
    this->GX = *GX;
    this->ft = *ft;
    this->gnorm = *gnorm;
    this->K = *K;
    this->kappa = *kappa;
    this->theta = *theta;
    this->dt = *dt;

    _ufc_form = const ufc::form* (new bloch_torrey_form_1());
  }

  // Destructor
  ~Form_1()
  {}

  /// Return the number of the coefficient with this name
  virtual dolfin::uint coefficient_number(const std::string& name) const
  {
    if (name == "phase")
      return 0;
    else if (name == "u_0")
      return 1;
    else if (name == "GX")
      return 2;
    else if (name == "ft")
      return 3;
    else if (name == "gnorm")
      return 4;
    else if (name == "K")
      return 5;
    else if (name == "kappa")
      return 6;
    else if (name == "theta")
      return 7;
    else if (name == "dt")
      return 8;

    dolfin::dolfin_error("generated code for class Form",
                         "access coeficient data",
                         "Invalid coeficient");
    return 0;
  }

  /// Return the name of the coefficient with this number
  virtual std::string coefficient_name(dolfin::uint i) const
  {
    switch (i)
    {
    case 0:
      return "phase";
    case 1:
      return "u_0";
    case 2:
      return "GX";
    case 3:
      return "ft";
    case 4:
      return "gnorm";
    case 5:
      return "K";
    case 6:
      return "kappa";
    case 7:
      return "theta";
    case 8:
      return "dt";
    }

    dolfin::dolfin_error("generated code for class Form",
                         "access coeficient data",
                         "Invalid coeficient");
    return "unnamed";
  }

  // Typedefs
  typedef Form_1_FunctionSpace_0 TestSpace;
  typedef Form_1_FunctionSpace_1 CoefficientSpace_phase;
  typedef Form_1_FunctionSpace_2 CoefficientSpace_u_0;
  typedef Form_1_FunctionSpace_3 CoefficientSpace_GX;
  typedef Form_1_FunctionSpace_4 CoefficientSpace_ft;
  typedef Form_1_FunctionSpace_5 CoefficientSpace_gnorm;
  typedef Form_1_FunctionSpace_6 CoefficientSpace_K;
  typedef Form_1_FunctionSpace_7 CoefficientSpace_kappa;
  typedef Form_1_FunctionSpace_8 CoefficientSpace_theta;
  typedef Form_1_FunctionSpace_9 CoefficientSpace_dt;

  // Coefficients
  dolfin::CoefficientAssigner phase;
  dolfin::CoefficientAssigner u_0;
  dolfin::CoefficientAssigner GX;
  dolfin::CoefficientAssigner ft;
  dolfin::CoefficientAssigner gnorm;
  dolfin::CoefficientAssigner K;
  dolfin::CoefficientAssigner kappa;
  dolfin::CoefficientAssigner theta;
  dolfin::CoefficientAssigner dt;
};

// Class typedefs
typedef Form_0 BilinearForm;
typedef Form_0 JacobianForm;
typedef Form_1 LinearForm;
typedef Form_1 ResidualForm;
typedef Form_0::TestSpace FunctionSpace;

}
#else 

// DOLFIN wrappers
#include <dolfin/fem/Form.h>

class Bloch_TorreyBilinearForm : public dolfin::Form
{
public:

  Bloch_TorreyBilinearForm(dolfin::Function& w0, dolfin::Function& w1, dolfin::Function& w2, dolfin::Function& w3, dolfin::Function& w4, dolfin::Function& w5, dolfin::Function& w6, dolfin::Function& w7) : dolfin::Form()
  {
    __coefficients.push_back(&w0);
    __coefficients.push_back(&w1);
    __coefficients.push_back(&w2);
    __coefficients.push_back(&w3);
    __coefficients.push_back(&w4);
    __coefficients.push_back(&w5);
    __coefficients.push_back(&w6);
    __coefficients.push_back(&w7);
  }

  /// Return UFC form
  virtual const ufc::form& form() const
  {
    return __form;
  }
  
  /// Return array of coefficients
  virtual const dolfin::Array<dolfin::Function*>& coefficients() const
  {
    return __coefficients;
  }

private:

  // UFC form
  bloch_torrey_form_0 __form;

  /// Array of coefficients
  dolfin::Array<dolfin::Function*> __coefficients;

};

class Bloch_TorreyLinearForm : public dolfin::Form
{
public:

  Bloch_TorreyLinearForm(dolfin::Function& w0, dolfin::Function& w1, dolfin::Function& w2, dolfin::Function& w3, dolfin::Function& w4, dolfin::Function& w5, dolfin::Function& w6, dolfin::Function& w7, dolfin::Function& w8) : dolfin::Form()
  {
    __coefficients.push_back(&w0);
    __coefficients.push_back(&w1);
    __coefficients.push_back(&w2);
    __coefficients.push_back(&w3);
    __coefficients.push_back(&w4);
    __coefficients.push_back(&w5);
    __coefficients.push_back(&w6);
    __coefficients.push_back(&w7);
    __coefficients.push_back(&w8);
  }

  /// Return UFC form
  virtual const ufc::form& form() const
  {
    return __form;
  }
  
  /// Return array of coefficients
  virtual const dolfin::Array<dolfin::Function*>& coefficients() const
  {
    return __coefficients;
  }

private:

  // UFC form
  bloch_torrey_form_1 __form;

  /// Array of coefficients
  dolfin::Array<dolfin::Function*> __coefficients;

};


#endif 


#endif
